### ISSUE TITLE
Does not run if you have .NET core 3.1 x64—Specifically needs .NET core 3.1 x86

### ISSUE THREAD

**Issue by Enchoseon** [Basicprogrammer10/2B2T-Queue-Notifier#4]
If you try to run the program with only .NET core 3.1 x64 installed, you will get the generic, "To run this application you must install .NET core" error message.

This does not happen if you install .NET core 3.1 x86.

**Expected behavior**
- Support for .NET core 3.1 x64... *or*
- A clearer error message & README edit explaining that the x86 version is required.

**Comment by connorslade** [comment]
Thanks for bringing this up. I don't have my Windows computer with me right now, so I will work on this when I can. :P

**Comment by connorslade** [comment]
![image](https://user-images.githubusercontent.com/50306817/127088970-a0df64a8-459f-4c22-99ad-e7156a8741b6.png)
Think I found the problem :P

**Comment by connorslade** [comment]
I made a new release with builds for x86, x64 and a Portable build.
[https://github.com/Basicprogrammer10/2B2T-Queue-Notifier/releases/tag/0.2.1](https://github.com/Basicprogrammer10/2B2T-Queue-Notifier/releases/tag/0.2.1)
