### ISSUE TITLE
i dont want it to use discord

### ISSUE THREAD

**Issue by HausemasterIssue** [Basicprogrammer10/2B2T-Queue-Notifier#5]
**Is your feature request related to a problem? Please describe.**
i dont like it using discord webhooks

**Describe the solution you'd like**
i want it to not use discord webhooks

**Describe alternatives you've considered**
using ur own website or something

**Additional context**
sex

**Comment by connorslade** [comment]
_webhook is webhook_

You can set it to send it to IP / URI you want, it's just that the format that is sends is intended for discord.
The webhook content looks like this: 
```json
{
    "content": null,
    "embeds": [
        {
            "title": "Σ's 2B2T Queue Notifier",
            "description": "**Queue Position:** `{{QUEUE}}`\n{{MNT}}",
            "url": "https://github.com/Basicprogrammer10/2B2T-Queue-Notifier",
            "color": "{{COLOR}}",
            "footer": {
                "text": "{{TIME}}"
            },
            "thumbnail": {
                "url": "https://i.imgur.com/K1KWFjR.png"
            }
        }
    ]
}
```

If you want me to add support for another system's webhooks, just say that.
Or if you're saying that I should make a website to allow you to remotely check your queue status, I'm not sure that enough people use this for me to put the time effort and money into that.
<br>
<br>
<br>
sex

**Comment by HausemasterIssue** [comment]
Ok, can you add restart notifs too? And to be honest the platform I would
prefer for webhooks is something like microsoft or google.

**Comment by DotsonEli** [comment]
ok dude shut the fuck up pay for it if you want this to work

**Comment by HausemasterIssue** [comment]
haha just use lolliriet bot, that shit can do 10x more things than you can
do, and we're not paying shit for it.

**Comment by connorslade** [comment]
I could add the restart notifications.

I'm not really sure what you mean that you would want webhooks for *microsoft or google*.
Webhooks are just HTTP requests, It's nothing special really, It's like going to the page in your web browser.

**Comment by HausemasterIssue** [comment]
ok then just make a webhook on some random website ig

**Comment by connorslade** [comment]
Do you have any suggestions for services that I should add webhook support for?

**Comment by HausemasterIssue** [comment]
which websites support them lol?

**Comment by connorslade** [comment]
What did you mean by `And to be honest the platform I would prefer for webhooks is something like microsoft or google.`

Clearly, you weren't asking for more services to be supported.

**Comment by HausemasterIssue** [comment]
yes i am retard congratulations, but what i clearly want it just any
webhook besides discord, it can be microsoft, google, your own, uh, just
anything besides big chatting platforms and social media sites, i'm sure
you can find a good one :)

**Comment by connorslade** [comment]
Oh, ok, that makes more sense :P
