### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by KinggDev** [Basicprogrammer10/2B2T-Queue-Notifier#6]
Idk which .net window x64 version dowload - host/cmd/desktop. Please help! Thanks

**Comment by connorslade** [comment]
I assume you got this figured out

**Comment by KinggDev** [comment]
Yes. Im guy from discord lol
I'm dumb

niedz., 14 sie 2022, 21:33 użytkownik Connor Slade ***@***.***>
napisał:

**Comment by connorslade** [comment]
Ok great
